apiVersion: apps/v1
kind: Deployment
metadata:
  name: risk
  namespace: staging
  labels:
    app: risk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: risk
  template:
    metadata:
      labels:
        app: risk
    spec:
      containers:
        - name: risk
          image: ghcr.io/haleema33/risk:staging-1.0.0
          ports:
            - containerPort: 8083
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: myesi-secrets
                  key: SBOM_DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: myesi-secrets
                  key: JWT_SECRET
          readinessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: risk
  namespace: staging
spec:
  ports:
    - port: 80
      targetPort: 8083
  selector:
    app: risk
  type: ClusterIP

